# Generated by Django 5.2.4 on 2025-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
                ('adults_quantity', models.IntegerField(verbose_name='Взрослые')),
                ('childs_quantity', models.IntegerField(verbose_name='Дети')),
            ],
            options={
                'verbose_name': 'Заброн',
                'verbose_name_plural': 'Заброны',
            },
        ),
    ]
